### ISSUE TITLE
请问能加个许可证吗

### ISSUE THREAD

**Issue by Pinghigh** [YidaozhanYa/fluent-css#1]
有个 GPL3 的项目想借用一下，能说明一下授权吗 :D

**Comment by YidaozhanYa** [comment]
欸？？这个只是我用开发者工具从 Fluent UI React 的 demo 上扒下来自己用的，根本没有考虑到有别人会去用 qwq
正经用的话，还是去用 [Fluent UI React](https://github.com/microsoft/fluentui) 吧。

**Comment by Pinghigh** [comment]
那我就当 MIT 的用了 qwq
就一个练手项目用用这俩元素

**Comment by YidaozhanYa** [comment]
我也是练手啦 qwq
刚接触 HTML，CSS 什么的，玩不来 React、Webpack 之类的高级玩意，就抄抄微软的高级玩意，自己用 qwq
